### ISSUE TITLE
patch for Unicorn?

### ISSUE THREAD

**Issue by aquynh** [cojocar/fuzzemu#1]
this looks like a nice tool, congrats! we linked to your project from our website now: http://www.unicorn-engine.org/showcase/

just wondering if you can send the patch for Unicorn upstream, so we can make it available for everybody? https://github.com/cojocar/fuzzemu/blob/master/patches/unicorn/0001-unicorn-partial-support-for-MCLASS-arm-cpu.patch

keep it up, cheers!

**Comment by cojocar** [comment]
Thanks for linking the project @aquynh ! It is still work in progress though. I plan to send the unicorn patch soon. However, it was not properly tested. I only tested it with a very small test set.

**Comment by aquynh** [comment]
we are going to release Unicorn v1.0 soon. will you send a pull req to include your patch?

**Comment by cojocar** [comment]
Done: https://github.com/unicorn-engine/unicorn/pull/700. However, the feature should be experimental. I don't have a thorough test case (it just works so far).
Although not a issue with unicorn, **capstone** reports, sometimes, an incorrect size of instruction. In the emulator I have some hacks to cope with this: https://github.com/cojocar/fuzzemu/blob/master/main.c#L176

**Comment by aquynh** [comment]
i think that is fine. if people have issues with this MCLASS support, they will report.

regarding Capstone bug, did you try with the "next" branch, which should be quite better than the "master" branch?

**Comment by cojocar** [comment]
No, not yet. Thanks for the tip!
